### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by RinRintech** [RinRintech/protospace-39853#1]
#URL
https://protospace-39853.onrender.com/

**Comment by motomuun** [comment]
@RinRintech さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー管理機能**

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
「こんにちは、〇〇さん」が重複しています。一つだけ表示されるように修正をお願いします。

**プロトタイプ編集機能**

- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できること**
「編集する」ボタンを押すと、下記画像のような「ユーザーの編集ページ」に遷移します。プロトタイプ編集ページに遷移するように修正をお願いします。

**その他**

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
トップページにリダイレクトされず、別のページに遷移します。トップページにリダイレクトされるように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by RinRintech** [comment]
動作確認ありがとうございます！

上記、すべて修正完了と挙動確認いたしました。
お手数ですが、改めてご確認お願いいたします。

**Comment by mo1015** [comment]
再提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by RinRintech** [comment]
ご確認ありがとうございました！

最終課題でもよろしくお願いいたします。
